describe source NAT fields
apache/cloudstack-documentation pull request #310
Opened 2023-04-14 15:56 UTC by DaanHoogland

to go with [cloudastack#6442](https://github.com/apache/cloudstack/pull/6442)

2023-04-14 15:57 UTC, DaanHoogland commented
@blueorangutan docbuild

2023-04-14 15:58 UTC, blueorangutan commented
@DaanHoogland a Jenkins job has been kicked to build the document. I'll keep you posted as I make progress.

2023-04-14 15:59 UTC, blueorangutan commented
QA-Doc build preview: https://qa.cloudstack.cloud/builds/docs-build/pr/310. (QA-JID 71)

2023-04-17 07:01 UTC, harikrishna-patnala requested changes
minor changes requested, otherwise LGTM

2023-04-17 07:01 UTC, harikrishna-patnala commented on source/adminguide/networking/advanced_zone_config.rst
> +   -  **IPv4 address for the VR in this Network**: The source nat address or primary public network address to use by the guest network. If not provided then a random address from the available pool
```suggestion
   -  **IPv4 address for the VR in this Network**: The source NAT address or primary public network address to use by the guest network. If not provided then a random address from the available pool of addresses wil be used.
```

2023-04-17 07:01 UTC, harikrishna-patnala commented on source/adminguide/networking/virtual_private_cloud_config.rst
> +   -  **IPv4 address for the VR in this Network**: The source nat address or primary public network address to use by the guest network. If not provided then a random address from the available pool
```suggestion
   -  **IPv4 address for the VR in this Network**: The source NAT address or primary public network address to use by the guest network. If not provided then a random address from the available pool of addresses wil be used.
```

2023-04-17 07:15 UTC, rohityadavcloud approved these changes

2023-04-17 09:10 UTC, weizhouapache commented on source/adminguide/networking/virtual_private_cloud_config.rst
> +   -  **IPv4 address for the VR in this Network**: The source NAT address or primary public network address to use by the guest network. If not provided then a random address from the available pool
@DaanHoogland 
IPv4 address for the VR in this VPC ?

2023-06-21 11:20 UTC, merged