Initial updates to add HPE Primera and Pure Flasharray documentation
apache/cloudstack-documentation pull request #363
Opened 2023-12-06 19:55 UTC by rg9975

Providing documentation for configuration of HPE Primera and Pure Flasharray plugins targeted for 4.19.

2023-12-07 12:38 UTC, shwstppr approved these changes
Not sure about the additional whitespace changes but looks okay to me

2023-12-07 13:11 UTC, andrijapanicsb commented on source/installguide/configuration.rst
> +      PreSetup. For KVM, choose NFS, SharedMountPoint,CLVM, RBD, FiberChannel or custom (for PowerFlex). For
The naming is not ideal, as fibrechannel can also (has been historically) configured outside of ACS, manuially, and just a Shared Mount Point would be feed to ACS. But leave it as it is.

2023-12-07 13:12 UTC, andrijapanicsb commented
white spaces probably removed automatically, for whatever reasons, nothing broken.

I have not reviewed the HPE-specific content, as I have no knowledge on it - so I assume this is OK.

2023-12-07 13:13 UTC, andrijapanicsb approved these changes

2023-12-11 06:33 UTC, rajujith requested changes

2023-12-11 06:33 UTC, rajujith commented on source/installguide/configuration.rst
> +This documentation assumes you have the following configured in your environment before configuring a storage pool in cloudstack:
The formatting is not proper. Same for Pure.
![Screenshot 2023-12-11 at 10 19 24 AM](https://github.com/apache/cloudstack-documentation/assets/5229147/9d08e568-5b48-4c37-b1d9-a7365dab23fe)

2023-12-11 20:21 UTC, andrijapanicsb commented
@rg9975 do you mind pls fixing these, so we can merge it?

2023-12-13 05:45 UTC, rajujith commented
@blueorangutan docbuild

2023-12-13 05:46 UTC, blueorangutan commented
@rajujith a Jenkins job has been kicked to build the document. I'll keep you posted as I make progress.

2023-12-13 05:47 UTC, blueorangutan commented
QA-Doc build preview: https://qa.cloudstack.cloud/builds/docs-build/pr/363. (QA-JID 179)

2023-12-13 06:20 UTC, rajujith commented
@rg9975  the bullet points are still not formatted properly.

2023-12-19 10:56 UTC, shwstppr commented
@rajujith can you please check now?

2023-12-20 04:23 UTC, rajujith commented
@blueorangutan docbuild

2023-12-20 04:24 UTC, blueorangutan commented
@rajujith a Jenkins job has been kicked to build the document. I'll keep you posted as I make progress.

2023-12-20 04:25 UTC, blueorangutan commented
QA-Doc build preview: https://qa.cloudstack.cloud/builds/docs-build/pr/363. (QA-JID 181)

2023-12-20 04:41 UTC, rajujith approved these changes
LGTM

2023-12-20 04:45 UTC, merged